#!/bin/bash -eu

. 00-common

#
# Initialize dpkg and apt-get.
#

# csak a DVD elkészítéséhez
mkdir -p "$DPKG_STATEDIR"/{info,updates}
touch "$DPKG_STATEDIR"/{available,status}
mkdir -p "$APT_STATEDIR"/lists/partial
mkdir -p "$APT_CACHEDIR"/archives/partial

apt-get \
	$apt_options \
	--allow-releaseinfo-change \
	-o Debug::NoLocking="true" \
	update
