#!/bin/bash -eu

. 00-common

case $DESKTOP in
	gnome)
		DESKTOPSTART=gnome-session
		;;
	mate)
		DESKTOPSTART=mate-session
		;;
	xfce)
		DESKTOPSTART=startxfce4
		;;
	kde)
		DESKTOPSTART=startplasma-x11
		;;
	lxqt)
		DESKTOPSTART=startlxqt
		;;
esac
	
# gdm autologin
if [ -s "$ROOTDIR"/etc/gdm/custom.conf ]; then
	echo "Set gdm autologin"
	sed -ri -e '/^\s*AutomaticLogin/d' -e 's/\[daemon\]/[daemon]\nAutomaticLoginEnable=true\nAutomaticLogin=uhu/' "$ROOTDIR"/etc/gdm/custom.conf
	# enable gdm
	echo "Enable gdm"
	if [ ! -L "$ROOTDIR"/etc/systemd/system/display-manager.service ]; then
		chroot "$ROOTDIR" systemctl enable gdm
	fi
fi

# lightdm autologin
if [ -s "$ROOTDIR"/etc/lightdm/lightdm.conf ]; then
	echo "Set lightdm autologin"
	sed -i -e "s/#pam-service=lightdm/pam-service=lightdm-autologin/" "$ROOTDIR"/etc/lightdm/lightdm.conf
	sed -i -e "s/#autologin-user=.*/autologin-user=uhu/" "$ROOTDIR"/etc/lightdm/lightdm.conf
	sed -i -e "s/#autologin-session=.*/autologin-session=$DESKTOP/" "$ROOTDIR"/etc/lightdm/lightdm.conf
	# enable lightdm
	echo "Enable lightdm"
	if [ ! -L "$ROOTDIR"/etc/systemd/system/display-manager.service ]; then
		chroot "$ROOTDIR" systemctl enable lightdm
	fi
fi

# sddm autologin
if [ -s "$ROOTDIR"/usr/lib/sddm/sddm.conf.d/sddm.conf ]; then
	echo "Set sddm autologin"
	mkdir -p "$ROOTDIR"/etc/sddm.conf.d
	cp "$DATADIR"/sddm/live.conf "$ROOTDIR"/etc/sddm.conf.d/live.conf
	if [[ $DESKTOP = "kde" ]]; then
		sed -i -e "s/User=.*/User=uhu/" "$ROOTDIR"/etc/sddm.conf.d/live.conf
		sed -i -e "s/^Session=.*/Session=plasma/" "$ROOTDIR"/etc/sddm.conf.d/live.conf
	else
		sed -i -e "s/User=.*/User=uhu/" "$ROOTDIR"/etc/sddm.conf.d/live.conf
		sed -i -e "s/^Session=.*/Session=$DESKTOP/" "$ROOTDIR"/etc/sddm.conf.d/live.conf
	fi
	# enable sddm
	echo "Enable sddm"
	if [ ! -L "$ROOTDIR"/etc/systemd/system/display-manager.service ]; then
		chroot "$ROOTDIR" systemctl enable sddm
	fi
fi

# lxdm autologin
if [ -s "$ROOTDIR"/etc/lxdm/lxdm.conf ]; then
	echo "Set lxdm autologin"
	sed -i -e "s/# autologin=.*/autologin=uhu/" "$ROOTDIR"/etc/lxdm/lxdm.conf
	sed -i -e "s/# skip_password=.*/skip_password=1/" "$ROOTDIR"/etc/lxdm/lxdm.conf
	sed -i -e "s/# session=.*/session=$DESKTOPSTART/" "$ROOTDIR"/etc/lxdm/lxdm.conf
	# enable lxdm
	echo "Enable lxdm"
	if [ ! -L "$ROOTDIR"/etc/systemd/system/display-manager.service ]; then
		chroot "$ROOTDIR" systemctl enable lxdm
	fi
fi

chroot "$ROOTDIR" systemctl set-default graphical.target
