#!/bin/bash -e

. 00-common

function hiba (){
		echo $1
		helptext=$(cat $DATADIR/help.txt)
		printf "\e[0;31m $helptext\n"
		exit
}

for i in "$@"
do
case $i in
    UBK*)
        DIST="$i"
        DISTVER="${i/UBK/}"
        export DIST=$i
        export DISTVER="${i/UBK/}"
        shift
    ;;
    ubk*)
        DIST="${i^^}"
        DISTVER="${i/UBK/}"
        export DIST=$i
        export DISTVER="${i/UBK/}"
        shift
    ;;
    gnome|mate|xfce|kde|lxqt|lxde|lumina)
        DESKTOP="$i"
        shift
    ;;
    --help)
        hiba
        shift
    ;;
    *)
    	hiba
    ;;
esac
done

if [ ! -d data/$DIST ];then
	hiba "Nem kezelt disztribúció: $DIST!"
fi

if [ -n "$DESKTOP" ]; then
    case $DESKTOP in
		gnome)
			export DESKTOP=gnome
			;;
		mate)
			export DESKTOP=mate
			;;
		xfce)
			export DESKTOP=xfce
			;;
		kde)
			export DESKTOP=kde
			;;
		lxqt)
			export DESKTOP=lxqt
			;;
		lxde)
			export DESKTOP=lxde
			;;
		lumina)
			export DESKTOP=lumina
			;;
			*)
			hiba "Hibás desktop paraméter, mely most a $2!"
			printf "\e[0;31m $helptext\n"
			exit
			;;
	esac
else
	export DESKTOP=mate
fi

if [ -f packages_cd.txt ]; then
	rm -f packages_cd.txt
fi
rm -f apt.log
rm -f installed_packages*.txt

mkdir -p $WORKDIR

isoarch="amd64"

export UHU_RELEASE_FULL="UHU-Linux ${DIST}-${DESKTOP^^}-${ISODATE//-}-$isoarch"
export release_file="${UHU_RELEASE_FULL// /-}"

cp "$DATADIR"/$DIST/packages.cd.base.txt $BASEDIR/packages_cd.txt.tmp
cat "$DATADIR"/$DIST/packages.$DESKTOP.txt >> $BASEDIR/packages_cd.txt.tmp
cat $BASEDIR/packages_cd.txt.tmp | grep -v '^-' >> $BASEDIR/packages_cd.txt
rm -f $BASEDIR/packages_cd.txt.tmp

export apt_sourcelist="-o Dir::Etc::SourceList="$DATADIR"/$DIST/sources.list"

for i in [0-9][0-9]-*; do
	if [ -x "$i" ]; then
		case "$i" in
		  *~|*.orig|*.rej|*.skip)
			;;
		  *)
			"./$i"
			;;
		esac
	fi
done
